name: Build simple-bar-launcher
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements-dev.txt
    - run: sudo apt update
    - run: sudo apt install libegl1 -y
    - run: ./freeze.sh
    - uses: actions/upload-artifact@v3
      with:
        name: simple-bar-launcher
        path: dist/simple-bar-launcher